# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!

pod 'CocoaLumberjack', '~>1.8'
pod 'JSONModel'

